# build environment
FROM node:alpine as builder

#RUN mkdir /usr/src/app
WORKDIR /usr/src/app

#ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package.json /usr/src/app/package.json 
COPY yarn.lock /usr/src/app/yarn.lock
COPY . /usr/src/app
RUN yarn run build --production

# production environment
FROM nginx:1.15.8-alpine
COPY default.conf /etc/nginx/conf/conf.d
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

