version: '3.7'

services:
  api:
      image: axis-flask/api-prod
      environment:
          CELERY_BROKER_URL: "redis://redis"
          CELERY_RESULT_BACKEND: "redis://redis"
      ports:
          - 5000:5000
      build:
          context: ./apps/api
          dockerfile: Dockerfile

  worker:
      image: axis-flask/worker-prod
      environment:
          CELERY_BROKER_URL: "redis://redis"
          CELERY_RESULT_BACKEND: "redis://redis"        
      build:
          context: ./apps/worker
          dockerfile: Dockerfile
